### ISSUE TITLE
Specify that users should search for case numbers, not e.g., names

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#135]
> When I enter in a name that does have a file number that does exist, it tells me I don’t have permissions, but when I enter in the name’s file number, it does open the record.  If you can only search reliably by file number, you should request that as your input.

**Comment by shanear** [comment]
@KHarshawat We need to investigate whether or not they actually use the names to search by. If not we can change the input instructions and punt on this for now.

If they do use the names... it's not a trivial change :(

**Comment by KHarshawat** [comment]
@shanear So far I think I've only seen users enter case numbers (as they are used to in VBMS). If we see or hear that users would like to search by name, we can add this as a future improvement but for right now this is a nice to have feature.  For now let's just make sure the language on the home page makes it clear to the user that the should search by ID like below.

![image](https://cloud.githubusercontent.com/assets/6335546/16717500/cad56960-46e4-11e6-8d93-4a1e51f0dc79.png)


Also instead of the word "Case ID" we should use whatever term VBMS uses in it's interface (e.g. File Number, etc). I don't know what it is off the top of my head.

**Comment by KHarshawat** [comment]
In an older mock I used the following language: 

![image](https://cloud.githubusercontent.com/assets/6335546/16717826/b268c724-46e8-11e6-976b-2ac56fdc56d4.png)
