### ISSUE TITLE
When a document isn't able to be downloaded, provide Doc ID

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#169]
The most useful information for a user to find a missing document is the VBMS document ID. We should include this in the errors tab with the filename.

**Comment by shanear** [comment]
@KHarshawat we can already query the DB for these IDs, and i think adding the Doc ID in the UI might confuse people. It's a pretty large, and looks like #{1asd23-231123-43aadsa-34adsad}

**Comment by KHarshawat** [comment]
Hm... we need to provide an easy way for the user to find this file individually in the eFolder via VBMS. @lakohl do you a chance to think this through?

**Comment by lakohl** [comment]
Can we provide the Doc Type and the date? This is what most users are used to seeing. We may still nee the doc ID though. See #168

**Comment by lakohl** [comment]
On second thought, I think if we give the user clear instructions to perform a search for the doc ID in VBMS that might work.

**Comment by shanear** [comment]
@lakohl just let me know the copy/design for this

**Comment by lakohl** [comment]
@shanear @KHarshawat @abbyraskin Here's a thought...
It seems that what is most important to users is the Doc Type and the Rev'd date. What if we surface those instead of the filename on the Prepare for Download page? 

Then, on the Retrieving page we could actually list our (much longer) filename -that users will also see when they download the the eFolder. (In that case the receipt date becomes redundant as it's also in the filename.) This could potentially help clarify what is happening... or not.

I couldn't figure out how to search by doc ID or filename in VBMS, (is this doable?) but I was able to sort by Doc ID.

Based on the rationale above, a suggestion for the erros page could be: 
<img width="427" alt="errors" src="https://cloud.githubusercontent.com/assets/4975959/19369592/65b0dbb6-9174-11e6-89a8-6daed1c4080e.png">

**Comment by shanear** [comment]
@lakohl I like that idea! Adding the doc ID to the errors page is what we'll do.
