### ISSUE TITLE
Include document type in filename

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#237]
Use the [VBMS docType listing](https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/other%20systems/VBMS/document_types.txt) to include the docTypes in the file names (the human-readable version, not the docType ordinals).

This can be tricky because that listing contains lots of characters that can't be used in filenames. Would be difficult to exactly match the VBMS naming conventions.

A few VBMS examples (from sanitized screenshots):
![image](https://cloud.githubusercontent.com/assets/16327036/19169410/5b1313fa-8be2-11e6-95ec-28cea7655115.png)
![image](https://cloud.githubusercontent.com/assets/16327036/19169424/761bb918-8be2-11e6-9c35-b0de26569e69.png)

More discussion in #158

**Comment by lakohl** [comment]
@orischwartz Sorry. You were right, there is another issue related to this I just surfaced: https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/168

**Comment by shanear** [comment]
I went ahead and assinged this to myself, let me know if you were working on this @orischwartz

**Comment by lakohl** [comment]
Suggestion is to start with our numbering system (with the first number being 0010 instead of 0000), then VBMS Doc Type, then received date: e.g. 0010_FormDD814_20160306
@KHarshawat what do you think?
See https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/168

**Comment by lakohl** [comment]
I would still like to associate the Doc ID with the file in the metadata (this allows it to be visible in Adobe Acrobat) but would prefer it did not appear in the file name.

**Comment by lakohl** [comment]
spoke to @KHarshawat about this today... It seems that we need to mostly stick to the current VBMS file naming convention, even though it is very lengthy. One exception would be that instead of the Vet ID# at the front end, we would add our numbering system  -to keep files in order. 

This would make the order as follows: 1)our numbering system, 2) Doc Type, 3) Date written as: 4-digit year, 2-digit month, 2-digit day, 4) Doc ID. e.g. 0010-FormDD814-20160306-D679800_tjjs-0824-34389hs-57959.pdf

@shanear Would it be a heavy lift to add the vet ID to the file name if in the future we decide to let employees download single files form the eFolder?

**Comment by orischwartz** [comment]
@lakohl This is one of the easier things to change so we can always revisit.

**Comment by shanear** [comment]
@lakohl Do we want to show the type name in the UI as well?

Heres a screenshot of that:
<img width="1554" alt="screen shot 2016-10-13 at 11 44 16 am" src="https://cloud.githubusercontent.com/assets/1596259/19356233/1b3fce36-913b-11e6-88bd-f5e4399c2e71.png">

**Comment by lakohl** [comment]
@shanear I would expect the Filename here to show the Doc Type and the Receipt Date column to show, well, the receipt date
