### ISSUE TITLE
Support more than 1 test user at a time

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#289]
Would be nice to have isolated user sessions in the dev environment. Currently there's a [single shared user](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/lib/fakes/test_auth_strategy.rb#L17) for all so e.g., giving two demos within 24 hours will show the old search history. 

Possible implementation: Use a unique [omniauth uid](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/controllers/sessions_controller.rb#L6) for each session. So instead of passing the hardcoded hash from `test_auth_strategy`, dynamically create one for in `RAILS_ENV=development`.

**Comment by shanear** [comment]
This should be handled by this:

https://github.com/department-of-veterans-affairs/caseflow/pull/444

We can add additional users if needed.

**Comment by shanear** [comment]
So I'm thinking that the user changer used for caseflow won't work for efolder express because they dont share the same url pattern.

This will also be an issue with Caseflow feedback. @askldjd it would be nice to have them all share a domain suffix like we do in uat/preprod/prod so we can share the user picker in Caseflow?
