### ISSUE TITLE
Store current_user as a thread local variable instead of BGSService

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow-efolder#315]
Currently, eFolder codebase has a few areas that are prone to race condition. Any type of `cattr` should been seen as a warning sign. Ideally, we want zero sharing among requests.

To address this issue, we probably need to do two things

 - [ ] Identify all memory sharing points
    - example: https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/controllers/application_controller.rb#L54
 - [ ] Create issue for each of them and address them. (could be merged if it is a architecture refactor)

**Comment by shanear** [comment]
I'm not actually sure we want zero sharing among requests.

We use the pattern of putting a using `cattr` to swap out Fakes from real dependencies. This configuration should affect the all app requests. (either it's always running in "fake" mode or always running "real" mode) This pattern works for that.

The reason this pattern bit us is because `BGSService` requires a `user` to authenticate, which is obviously not constant for each request. As far as I know `current_user` is the only variable cross-cutting enough to warrant being a global request variable. We can take one of two routes: 

1) `User.current` a global variable that is scoped to each request. We'll need to store this on a thread local variable using `Thread.current`.
2) Pass `current_user` everywhere it's needed. The way rails is wired right now I could see this getting pretty verbose, but it's certainly more pure.

Also, to avoid request specific data, we really need to avoid any sort of class configuration in `before_filters` in `ApplicationController` (like this)[https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/controllers/application_controller.rb#L54].

The issue here is that we'll have to figure out a better way of how to instrument the application in our feature tests. I will take a look into that.

cc/ @jd

**Comment by askldjd** [comment]
Working with @shanear on the bug yesterday, I think in Rails/Puma threading model, sharing in thread-local-storage is okay. The user object is a good use case.

**Comment by joofsh** [comment]
Based on my researched into puma yesterday, it does appear safe to use thread local variables. I agree `current_user` is probably the one variable that makes sense as a Thread local variable. I'd love for us to move from `Thread.current[:download_bgs_service]` to `Thread.current[:current_user]`. I think this will scale better to other services that also need access to the current user

**Comment by shanear** [comment]
Agreed @joofsh, `Thread.current[:download_bgs_service]` was just the quickest bandaid I could get out there to stop the bleeding.

Will follow this issue up with a pull request that stores just the current user a as a Thread local variable.

**Comment by joofsh** [comment]
Sounds perfect. Thanks @shanear 👍 🇺🇸

**Comment by askldjd** [comment]
Closing this since it is no longer relevant.
