### ISSUE TITLE
Solve with sensitive document errors in production

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-efolder#395]
So some of the document errors we've been getting are due to them being sensitive documents in VBMS.

Right now, we just call them errors (and don't tell them the cause). There might be a more user friendly way to deal with these, and also don't record them as errors in our stats page.

See original conversation here: https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/330

**Comment by aroltsch** [comment]
Looking at February 2017 because this month had the most document errors. There are 499 document errors for the month of February, however, there are only 20 actual downloads that are associated with these failed documents:
```
Document.where(download_status: 2, created_at: start_time..end_time).map(&:download_id).uniq.size
=> 20
``` 

Next step: Looking at the status for these downloads.

**Comment by aroltsch** [comment]
#### Download id: 8126 ####
Failed with 1 document error due to the following: message="CMSERR0023 - The document ID <document_id> does not exist."
#### Download id: 8150 ####
No failure 
#### Download id: 9117 ####
Failed with 1 document error. Checked VBMS production and this document fails to preview there as well: Failed to load PDF document.
#### Download id: 9390 ####
Failed with 7 documents. Checked VBMS production and these documents fails to preview there as well: Failed to load PDF document.
#### Download id: 9417 ####
Failed with 1 document. Checked VBMS production and these documents fails to preview there as well: Failed to load PDF document.
#### Download id: 9646 #### 
No failure
#### Download id: 9997 ####
no failure 
#### Download id: 10016 ####
no failure 
#### Download id: 10017 #### 
no failure
#### Download id: 10018 #### 
no failure 
#### Download id:  10019 ####
no failure 
#### Download id:  9996 ####
no failure 
#### Download id:  10020 #### 
no failure 
#### Download id:  10222 ####
References the same file number as #4
#### Download id: 10308 ####
Failed with 1 document error. Checked VBMS production and this document fails to preview there as well: Failed to load PDF document.
#### Download id:  10551 ####
#### Download id:  10573 #### 
References the same file number as #16
#### Download id:  10600 ####
#### Download id:  10681 ####
Failed with 1 document error. Checked VBMS production and this document fails to preview there as well: Failed to load PDF document.
#### Download id:  11571 ####
No failure

**Comment by aroltsch** [comment]
Solution: save document errors in the DB so we can easily track these.

**Comment by aroltsch** [comment]
Some document errors are caused by:
```
NoMethodError: undefined method `content' for nil:NilClass
from /Users/vhaisaroltsa/dev/connect_vbms/lib/vbms/responses/document_with_content.rb:13:in `create_from_xml'
```
This error happens when the document is empty.

**Comment by amprokop** [comment]
@aroltsch— as per discussion in sprint planning, you'll loop in Lara to talk to RMC and Nicholas, then post here. Thx!

**Comment by kierachell** [comment]
**PASSED**
```
error_message: "VBMS::ClientError::Connection reset by peer - SSL_...">
```
Being capture, cool
