### ISSUE TITLE
Very large 3GB zipfile fails to download to the user's computer

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#470]
Very large zipfile fails to download to the user's computer. Investigate why this is happening. 

Steps to reproduce:
1.  Find a very large efolder or you can ask Anya for a file number
2. Download efolder using eFolder Express
3. Click download/save zip file to the local computer and observe that it fails mid way

See: https://github.com/department-of-veterans-affairs/appeals-support/issues/133

**Comment by aroltsch** [comment]
Investigation:
Locally I am able to download 3GB files successfully. In production the file fails to download probably due to an application server having a session timeout.

**Comment by aroltsch** [comment]
Steps to reproduce in preprod:
1. Search for a file number (PREPROD) 123111772
2. Download efolder
3. Once downloaded, save zip file to your local computer and observe that it fails mid way

**Comment by kierachell** [comment]
123111778 on preprod has about 2.5k documents

**Comment by askldjd** [comment]
There are two issues discovered:
1. After 1GB of download, Nginx may kill the connection. This has been addressed in https://github.com/department-of-veterans-affairs/appeals-deployment/pull/594.

2. There is a fundamental design issue for large file. If the EC2 instance does not have the zip file on disk, it may fetch from S3. If the file is large, it may exceed the HTTP timeout.
See https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/475

Closing this issue because it is two issues in one.
