### ISSUE TITLE
Give eX to Contract Exam vendors

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#624]
Contract Exam vendors have asked for access to eX. Original ask was for 12 VBA contractors on 9/20 that was upped to 150 people. Still learning more about the other 138.

Tracking rationale here

**Comment by lakohl** [comment]
Contract Exam Vendors

Contract exam vendors are comprised of non-VA admin contractors and clinicians.

RVSRs at ROs  send Exam Requests to the vendors (by ftp) via CATS (Centralized Admin Transaction System) asking them to review medical docs and to perform medical examinations of Veterans. 

The RVSR Exam Request tells the clinician which records they need to review. The contractor’s admin (triage group) downloads the efolder files from VBMS/VVA, to their own system, which is where the clinicians’ access the Veteran’s records. The clinician/examiner however is not limited to looking at the files in the exam request. 

Admin contractors also schedule medical exams for their clinicians. It’s important that the requested files are available for the clinician to review before and during the medical exam. It’s a waste of the examiner’s time (and the Veteran’s!) if they don’t have the records during the exam.

Previously:
The Contract Exam Vendor admin staff used the VBMS ‘tools’ tab to check a box on the VVA file they needed and then they were able to download it. 

Now:
On 9/10/17 VBMS released an update that unintentionally removed access to the download e-doc tools check box for all VVA files. As a result, users must now open every document they need before they can download it.

**Comment by lakohl** [comment]
* 'The clinician/examiner however is not limited to looking at the files in the exam request.' 
_Wrote to Chelsey Kondrak to confirm exactly which files the clinician has access to._

She wrote back:
>The VSR/RVSR will tab records for the clinician/examiner’s review.  For example, they may tab certain service treatment records, personnel records or private treatment records.  However, the clinician/examiner is not limited to reviewing only the tabbed records.  If Vendor finds other records within the VBMS eFolder or under the Virtual VA tab that may be pertinent to the condition being examined, then they should also review these records.   
 
>The Contractors’ admin triage group should be downloading all records pertinent to the claimed condition(s).  If they see records that may reference the condition being examined but they weren’t tabbed by the VSR/RVSR, then they may download these records as well.  In some cases, the downloading may involve the entire eFolder.

**Comment by raquelromano-gov** [comment]
Stumbled on this and interested b/c it may be relevant to the disability claims application work getting started on vets.gov. Thanks @lakohl for putting this detailed info in github for others to find!
@randallweidberg-gov @lmcochrn-usds (can't tag ad hoc folks working with us on this b/c they don't have access to this repo, so will pass along to Rachael R. and Alex T.)

**Comment by lmcochrn-usds** [comment]
thanks @raquelromano-gov!

**Comment by lakohl** [comment]
follow-up conversation scheduled for today with Karla Leal

**Comment by mattwilcut** [comment]
**I request to have addressed, here out in the open, the rollout strategy with regards to the release of eX to the various parties of the overall VA claims system.  As discussed below, I believe this is a proper location of this comment/question because it addresses the propriety of approving access to this type of party (contract examiners) prior to the approval of access to other parties, arguably in higher _need and consideration_ of the access.**

**I have emailed the Caseflow support email but for weeks have received no response to my related inquiry.**

By my count, eX has been provided to certain staff at:
- Appeals Team/Ratings Team at certain Regional Offices
- Office of General Counsel
- Records Management Center
- Board of Veterans' Appeals

I believe philosophically, morally, and legally (if only to be at least in line with the spirit of the law and the overall concept of providing the necessary government services related to benefits for Veterans) that Veterans, _through their representatives_, should be provided this capability - in their current categorization by the VA as "contractors" when it comes to access to PIV cards, VBMS, etc. - before _contract examiners_ are provided it. 

#570 - Why was this delayed? The delay was supposed to last until September which has come and gone.  What is the timetable for this all representatives to have access to Reader and to have eX enabled?  What does #1416 of /appeals-pm/ say on this topic?


**Why Veterans Representatives need eX BEFORE Contract Exam Vendors**

Aside from the obvious arguments as to why a Veteran and their representative would benefit from a one-click solution to obtaining the C-File, there is the yet-to-be-acknowledged (just from what I can see, not saying it hasn't occurred - however, #570 is lacking in substantive discussion) argument that this is all in the context of the Veteran's claim and that any improvement made in assisting a Veteran from advancing their claim more efficiently will necessarily carry that efficiency into all of the processes that follow downstream.  The government did not initiate this process, the Veteran did.  The government in most cases does not have the burden of demonstrating eligibility and entitlement, the Veteran does.

Opening up access to eX to Veterans through their representative is a much needed efficiency and that efficiency would carry over directly to contract exam vendors, even without their own access to the feature being provided first.  Most importantly, the reverse is not true.  Placing this wonderful feature in the hands of the contract examiners first sets up a disadvantage for the Veteran to respond or have responded.  As an example, Veterans and their representative should always strive to provide not just the primary evidence (military and medical records) but secondary authority that clearly summarizes and synthesizes all the evidence of record to date.  For the benefit of contract exam vendors and VA examiners alike, a medical chronology authored by the Veteran or their representative would enable them to more quickly review cited documents specific to the date and page of the pdf.  Separate chronologies can be made for military and post-service records, private medical treatment and VAMC treatment, and of the claims' progression overall.  And this is all just to speak to preparation for the examiner's review, not to mention preparation of a supplemental claim, DRO review, and BVA review.  

Another topic that improves with this feature being provided is training of representatives by other representatives, specifically in the context of pro bono representation.  Another area of improvement is when time is of the essence (Veteran has an examination or DRO/BVA hearing scheduled soon - sooner than a Privacy Act request would permit the VA to respond).

I could go on and on but I believe you get the point.  If only the side of the adjudicators (VA) is armed with these beneficial improvements, even temporarily, then I believe the spirit of the government and the spirit of the USDS is being lost and it becomes adversarial by default.  It enables _better_ denials for imperfect or overly complex, but not meritless, claims.

**Comment by nicholasholtz** [comment]
@mattwilcut Thank you for your feedback. We share your desire to improve and expedite the appeals process for Veterans, and appreciate your advocacy on their behalf. We are striving every day to build tools that empower VA employees with technology to increase timely and accurate appeals decisions, with the ultimate goal of improving the Veteran experience. This includes getting copies of Veterans' claims files to them in a timely manner; one of the primary purposes of eFolder Express is to enable VA to provide timely FOIA and Privacy Act responses to Veterans. Issue #570 is in furtherance of that purpose. That ticket's purpose is to control the integration between eFolder Express and Virtual VA, one of the databases used by VA to store Veteran claims file information.

While we ultimately may be able to provide Veteran-facing technology, including in collaboration with the DSVA team working on http://www.vets.gov, at this time we are restricted by VA policies in place to protect Veterans. Veterans' claims files often contain Personally Identifiable Information (PII) for persons other than the Veteran him/herself, including other Veterans; that information must be redacted before being provided to the requesting Veteran. 

Again, thank you for your feedback, and please do not hesitate to provide more. 

Nicholas Holtz
Digital Service at VA - Appeals Lead

**Comment by mattwilcut** [comment]
@nicholasholtz Thank you for your considered response.  As an initial matter, I want to say that I think the USDS and 18F are two of the most wonderful, recent government initiatives.  I'm a geek first and a Veterans' advocate second.  I came very close to a career designing and coding solutions for e-government before I got on the path of assisting Veterans.  Whenever I read on HN or [elsewhere](http://blog.samaltman.com/the-us-digital-service) about what the USDS or 18F is doing or who has joined their ranks, I have always considered it a show of progress.

That said, I still can't give up on my current quest to learn more about the overall plan for the rollout of Caselow/Reader/eX access to the several parties involved in VA claims because I don't see a current plan that signals progress, at least not in the same sense as what I thought USDS stands for.  @lakohl recently closed #534 and #570, so this remains the sole open issue currently as to the rollout of access.

#543 appears to have been the first stage of the rollout of eX and, as you mentioned, will get copies of Veterans' claims files to them in a timely manner through responses to Privacy Act requests.  No issues or problems with that, just the opposite.  Not everyone has a representative who can get them a copy of their electronic claims file upon request and not everyone has a computer even if they did, so requests like these are immediately improved when those VA employees have that access.  Hats off!

But from there you made the curious statement that VA policies restrict Veteran-facing technology at this time, in order to protect their PII.  This is plainly false but I will assume it is because you are not aware of just how false it is.  Right now, as I type this I'm logged into the VA's system through a Citrix gateway - and yet I'm not a VA employee.  As I mentioned earlier, the VA categorizes Veteran representatives as more like VA contractors.  I have a PIV card that enables me to login to the VA's system, use a VA email (and encrypt my emails containing PII to others), look up any VA employee's contact info, and access my client's efolder through VBMS.  It actually took me a full year, three sets of fingerprinting and background checks to my then and former supervisors to get me that PIV card.  I've attached a picture of me using the Caseflow demo while logged into the VA's system.  

![demo running](https://user-images.githubusercontent.com/32416289/31312793-8145a018-ab9b-11e7-96ca-e3ba9bbc61fb.png)

So to say that access is currently prevented by security/privacy policies is clearly erroneous because all it would take to provide safe, secure access as I've requested for all representatives is to put the login to Caseflow/Reader/eX behind the CSS login portal.

![css login](https://user-images.githubusercontent.com/32416289/31312794-8146e18a-ab9b-11e7-9dcf-f9a4d1eb9692.png)

To further detail why I think its important that this is done, consider that the USDS Playbook play 1 begs the USDS to ask what do the people need and to address the whole experience.  Right now, and again this is partly because of a lack of transparency where I can't see things in /appeals-pm/ and other private repositories, all I see being advanced here at the beginning of these solutions is what would address the VA's needs in developing the claims, not what the people (whether that's taxpayers or Veterans) would be most likely to support in assisting Veterans advance their claims.  It's not like I'm not asking for the opposite either - that only the Veterans and their representatives have these solutions (they are great looking and well designed solutions by the way) but I do think that they should be provided to the Veteran if they're going to be provided to the VA.  A level playing field is required.  Otherwise, the VA has advantages in its review of the claims process over what the Veteran and his representative have when they are the ones who have the ultimate burdens of proof.  It would be like providing defense attorneys access to PACER but not prosecutors/plaintiff's attorneys.  

When this rolls out to BVA VLJs and attorneys, is their simultaneous access being provided to the claimant and their representative in those cases?  If not, then even inadvertently and innocently, the USDS has created an imbalance of power.  Just put it behind the CSS login as I mentioned and you've solved what was your cited main barrier to access.
