### ISSUE TITLE
eFolder | ActiveRecord::StaleObjectError: 

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow-efolder#650]
Currently: Looks like downloading has gone stale.

Browser: "Other"
Env: Prod

Message: ActiveRecord::StaleObjectError: Attempted to update a stale object: Download

Line 55: `download.update_attributes!(manifest_fetched_at_name => Time.zone.now)`

Sentry Error: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/520/

**Comment by mmlumba** [comment]
Another sentry error: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/554/

**Comment by amprokop** [comment]
so here’s the current state of things. See https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/08b39cebe54773d062fba404e4f29894eaace5c7/app/models/download.rb#L275
stale object errors are there purposely to avoid race conditions causing data mishmash. we rescued them here and in a couple more places. this solved 95%+ of the problem for our users — previously reader users were getting errors/

then we added more rescues in other places. https://github.com/department-of-veterans-affairs/caseflow-efolder/search?utf8=%E2%9C%93&q=rescue+ActiveRecord%3A%3AStaleObjectError&type=


there is still one StaleObjectError hanging around. it is a rare one, because. it only happens in the error block. our code is like:
 ```def method!
# stuff
rescue SomeError
  update_object_to_reflect_error
rescue StaleObjectError
end
```


we still get a few stale object errors in the `update_object_to_reflect_error` call.


so if we wanted to it could be



 ```
def method!
# stuff
rescue SomeError
  update_object_to_reflect_error
end
```
then when we call it:

 ```def other_method
   begin method!
   rescue StaleObjectError
   end
end
```

i think that would fix the current staleobject error. but it doesn’t seem that common. 

https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/554/events/

it's a little like whack-a-mole. once you rescue it in one place it starts happening further in code execution. so be aware of that.

**Comment by alisan16** [comment]
This hasn't been updated in 2 years. Closing.
