### ISSUE TITLE
Moving away from the Downloads table

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow-efolder#670]
This was created as an alternate option to the refactor proposed in https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/626. It's definitely not complete or done. Thoughts and quibbles welcome. Feel free to edit.

## Context

Same as https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/626. To summarize: 

- The Downloads table is overloaded
- Race conditions related to it cause StaleObjectErrors
- UI code paths and API code paths are in a kind of Gordian knot
- We've potentially drifted away from the time when the name "Download" was good — it made sense when we were only serving single ZIP files containing lots of documents

## Overview

The refactor proposes in https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/626 gets us to a desirable place in the end, but getting there will result in a number of painful and incremental steps. We have the advantage that the data in the Downloads table has a very short lifespan, and we only need to preserve it for auditing purposes. We should consider instead creating new tables, referring to them in v2 of our API, and only backfilling data into them where necessary.

## Moving away from the Downloads table

A row in the Downloads table currently represents something like "The status of the current attempts to talk to VBMS and VVA and obtain lists of the documents in both services, as well as some accompanying denormalized data about the Veteran".  

### DocumentList

Records in this table are mutable, and represent the most recent state of our document list. Each document has a pointer to a DocumentList. The eFolder ZIP file also will have a pointer to a document list.

```
  create_table "document_lists" |t|
    t.string   "file_number"
    t.string   "source"      # (VBMS or VVA)
    t.datetime "created_at",                                      null: false
    t.datetime "updated_at",                                      null: false
    t.string   "veteran_last_name"
    t.string   "veteran_first_name"
    t.string   "veteran_last_four_ssn"
    t.integer  "zipfile_size",          limit: 8
  end 
```

### DocumentListLogs

```
  create_table "document_list_logs" |t|
    t.integer  "document_list_id"
    t.datetime "started_at"
    t.datetime "succeeded_at"
    t.datetime "errored_at"
    t.integer  "user_id"
    t.datetime "created_at",                                      null: false
  end
```

Records in this table are never mutated. So of "started_at", "completed_at", "errored_at", only one will be ever filled out. When we want to refresh the document list for a file number, we'll first check if there are already requests open to VBMS/VVA for document lists. If there are requests open, we can avoid sending more requests. If we still need to start a new document fetch request, we can make two DocumentListLog records, one for VBMS, one for VVA. Then, when the requests finish, we'll create two new DocumentListLog records, one for VBMS, one for VVA, with "succeeded_at" or "errored_at" filled out. Our application code will abstract away the query complexity here. We can answer questions we can't easily answer now, like:

- Are we already requesting the documents list from VBMS?
- Did our previous request for the documents list to VVA fail?

We've already downloaded a ton of documents. We can backfill our new tables with those documents as needed without a migration. When a caller requests a document list from the v2 API, we can:
- Create a new `DocumentList` 
- Find the `Download` record with the same file number
- Find the documents associated with that Download row
- Associate those documents with the `DocumentList`

## Open Questions
- Should we take the same approach for the Documents tables (as Mark suggested)?
- Do we even need the mutable table, or should we go fully immutable?

**Comment by shanear** [comment]
Yeah, I'm definitely in agreement with this approach, with a couple tweaks:

1. I would only save a `DoccumentListLog` for UI downloads. This is the main problem now. The API is tangled with a bunch of code that was meant for the UI. We will still need the UI logic though. So lets encapsulate it in `DocumentListLog`.
1. I would definitely make `DocumentList` immutable. It will be way way simpler, and actually auditable. For instance, if we want to know the exact list of documents we downloaded from FOIA request 3 months ago, we would be able to produce that if `DocumentList` is immutable. If it's mutable, the `DocumentListLog` is pointing to a `DocumentList` that isn't actually representative of what was downloaded. Seems bad.
1. In order to make it immutable, we just have a expiry range on all `DocumentList`s. We trigger a new download if there isn't a completed `DocumentList` within the expiry range.
1. Those `StaleObjectError`s are there for a reason. Don't think that simply starting over alone will help you get rid of them, or the problems that would be caused if they weren't there.
1. I'd call it `Folder` instead of `DocumentList`. and `FolderDownload` instead of `DocumentListLog`. Log is the worst word to use when naming a table or class. Every thing is technically a log lol.

We'll probably want to keep developing the nitty gritties of this plan, but this is a very nice start 💯

**Comment by mdbenjam** [comment]
Seems in line with what I was proposing so I'm on board! A couple of notes:

1) I would make DocumentList immutable and determine if the zip_file size needs to be stored in the DB. That is the only value I see reasonably changing. Also zip_file size can't really live in this table since the zip file contains docs from two DocumentLists (VVA and VBMS).
1) To Shane's 2nd and 3rd point. While I think DocumentList should be immutable, I don't think we should freeze the document objects that point to the DocumentList. If we want to store how many docs were downloaded in the DocumentListLog, I think that makes sense, but I think there should be a 1:1 mapping of DocumentList's to Veteran's case files. Having an expiration to these records seems to add complexity and I'm not sure we get much from being able to audit FOIA requests.
1) @shanear I'm curious about the stale object errors. Why doesn't this help eliminate them?
1) Alex, I think you're right that we don't need to split up the Documents table.
