### ISSUE TITLE
[FE] Error Messaging for Hanging UI

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-efolder#675]
##  Story
As a eFolder Express user, when a download of an eFolder is timed out, I want to see an error message with appropriate next steps instead of an endless spinning icon. 

Steps to re-produce (locally):
1. Start rails s for eX, don't start Sidekiq
2. Search for any DEMO number, watch the spinner going forever. 

## Acceptance Criteria
- Verify that the below "We couldn't find this folder." error message is displayed when the request times out after the back end 
- Verify that the error message "We couldn't find this efolder" is in accordance with the message styling in the style guide.
- Verify that the copy below the error message reads " You can go back to the home page and Search for another efolder. If you continue  to experience problems, please use the Send feedback link to submit a ticket."
- Verify 'Search for another efolder' is a link that takes you back to the home page
- Verify that 'Send feedback' is a link that opens feedback 

## Mocks 

![image](https://user-images.githubusercontent.com/32683958/33615641-a49b1670-d9a8-11e7-8198-85c96b940ab0.png)

**Comment by Chingujo** [comment]
@lakohl 

Is this good to go? Took the stylings from the style guide and mock reflects the copy with the highlighted actions as links

Thank you =D!

**Comment by aroltsch** [comment]
Add steps to reproduce it

**Comment by lakohl** [comment]
@Chingujo Adjusting copy slightly.
<img width="719" alt="screen shot 2017-11-20 at 2 15 30 pm" src="https://user-images.githubusercontent.com/4975959/33036728-4e610eb0-cdfd-11e7-8593-4d395caace84.png">

**Comment by Chingujo** [comment]
Thanks @lark!! Updated the ac and the mock :)

@lowellnava My understanding was that we would eventually have to determine a timeout but that there isn't a BE ticket yet. However, Anya mentioned there may be a front end approach to this and we could build out the UI end.

@aroltsch to confirm or deny :)

**Comment by lowellrex** [comment]
This case will arise when a sidekiq job throws an exception and the job is terminated without changing the Download's status from fetching_manifest. The solution here will be to catch all StandardErrors on the backend and change the Download's status to some error status if the current status is fetching_manifest. The front-end will display the message if the download's status is set to that error status.

**Comment by lowellrex** [comment]
Updating the mock to reflect the line breaks as rendered in chrome on my machine.

![image](https://user-images.githubusercontent.com/32683958/33615641-a49b1670-d9a8-11e7-8198-85c96b940ab0.png)

**Comment by Chingujo** [comment]
Thanks @lowellrex!!

Once the color is changed and the padding on the left and right is shrunk like the style guide reference below...should be good to go!

<img width="667" alt="screen shot 2017-12-05 at 10 01 13 am" src="https://user-images.githubusercontent.com/23316107/33616429-db4fa346-d9aa-11e7-9cd0-849d91996091.png">

**Comment by astewarttistatech** [comment]
@Chingujo Is this only to be validated in Dev or will this change be able to work in all available testing environments?

**Comment by astewarttistatech** [comment]
**FAILED**

Spinner goes on pass 5 min (300000ms)


<img width="1430" alt="screen shot 2017-12-06 at 9 24 38 am" src="https://user-images.githubusercontent.com/23038505/33666266-720ce3a4-da67-11e7-8284-726a1c767eb8.png">

**Comment by lowellrex** [comment]
There are a few different ways that we could end up in a situation where the efolder UI search results page displays a spinner forever.

1. Client loses connection to the server
1. Sidekiq server goes down
1. Job being executed through sidekiq fails in an unexpected way

The first situation I do not believe we need to handle because it is either a problem on the end user's computer (lost connection to the internet), or with the efolder web server itself is unavailable. If the computer loses the connection to the internet, there will be other indicators to the user that the internet is unavailable and I expect they would retry this request when confronted with the infinite spinner. If the efolder web server is down, we will be alerted and will be working vigorously to get it back up and running as quickly as possible (seconds?). I don't think either of these situations is important enough to warrant solving, however if we wanted to we could display a javascript alert or something else similarly light. Redirecting to different page and updating the database to reflect that this search failed both require connections to the backend, so those solutions would not work.

The second situation is similar to the first. If the sidekiq server is down our application is not working. We will be working to restore service as quickly as possible (once again, hopefully seconds). The infinite spinner in the--fingers crossed--rare case when sidekiq dies may be an appropriate indicator to the end user that something is wrong on the backend. The solution to such a problem would be similarly light and incomplete to the approach proposed to resolve the first issue. Additionally, when the sidekiq server does come back online, the search could successfully complete and the database would indicate a success when our users are really presented with a failure. I think this is a mismatch we want to avoid.

As such, we are only addressing the third scenario now since it seems the most likely and most consequential. Sidekiq jobs DO occasionally fail without updating the download's status in the database. Because they don't update their status in the database, we get this infinite spinner (the front-end function pings the web server to see if the status has changes and reloads the page when it does).

## Test plan

In order to reproduce this behavior (and not modify the code to make it happen), you could do the following.
* Stop the sidekiq server
* Initiate a search (enter some ID in the search box and click "Search")
* Observe the spinner
* Update the status of the download record you just created in the database from 0 to 9
* The page should reload within a minute and you should see the screen in the original ticket

**Comment by kierachell** [comment]
**PASSED**
#### Simpler test plan:
- Start a download
- Go to Sidekiq UI
- Kill workers
- See the job restart

<img width="1004" alt="screen shot 2017-12-13 at 8 33 52 am" src="https://user-images.githubusercontent.com/18075411/33941415-894aa2b2-dfe0-11e7-8e8c-61599bc293d0.png">
<img width="648" alt="screen shot 2017-12-13 at 8 33 55 am" src="https://user-images.githubusercontent.com/18075411/33941416-89787dfe-dfe0-11e7-9c57-6197dac12de3.png">
<img width="983" alt="screen shot 2017-12-13 at 8 34 01 am" src="https://user-images.githubusercontent.com/18075411/33941417-89a6acce-dfe0-11e7-812e-e84c65cecf31.png">
<img width="1290" alt="screen shot 2017-12-13 at 8 34 14 am" src="https://user-images.githubusercontent.com/18075411/33941418-89d11374-dfe0-11e7-9186-67f12af373e7.png">
<img width="1336" alt="screen shot 2017-12-13 at 8 34 18 am" src="https://user-images.githubusercontent.com/18075411/33941419-89f60fda-dfe0-11e7-8471-0d51e6bea7c1.png">
