### ISSUE TITLE
BGS Service - current user is nil

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#704]
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/601/

Investigate why current user is nil in the Request Store.

**Comment by kierachell** [comment]
### Download:
```
#<Download id: 62541, request_id: nil, file_number: "******", status: 4, created_at: "2017-11-14 12:53:48", updated_at: "2017-11-15 09:16:32", lock_version: 545, manifest_fetched_at: "2017-11-14 12:53:56", started_at: "2017-11-15 09:16:32", completed_at: nil, veteran_last_name: nil, veteran_first_name: nil, veteran_last_four_ssn: nil, user_id: 714, zipfile_size: nil, from_api: true, manifest_vva_fetched_at: nil, manifest_vbms_fetched_at: "2017-11-14 12:53:56">
```
- From the lock number it seems this thing died a while ago:

### User:
- in eFolder:
```
#<User id: 714, css_id: "BVAKALLEN", station_id: "101",
```

- From API suggests it came from Reader:

```
User id: 1135, station_id: "101", css_id: "BVAKALLEN"
```

### Set user and bgs service:

- `fetch_veteran_info` requests succeeds:
```
FINISHED BGS: fetch veteran info for vbms id: ******:   0.010000   0.010000   0.020000 (  1.039297)
```

- Clearly the user has a station, why was it not passed to eFolder?
- The Download shows that veteran info is incomplete, probably because the BGS request never sailed.
- Is there an asynchronous race condition between BGS request and creating a new User in eFolder DB?:

- eFolder user created at: `created_at: "2017-11-14 12:40:34"`
- Download created at: `created_at: "2017-11-14 12:53:48"`
- Reader user created at:  not available

**Comment by aroltsch** [comment]
That's interesting.. download shows it is from_api but the error came from DownloadFilesJob which is actually a UI job (not the API)

**Comment by kierachell** [comment]
**PASSED**

because that's how I actually test the backend code as documented in QA repo
