### ISSUE TITLE
[BE] Move eX Sidekiq jobs to SQS

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#718]
Work with Sunil on this. 

Check out the discussion here: https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/669
Check out this most mortem: https://github.com/department-of-veterans-affairs/appeals-deployment/issues/1022

AC: All eX Sidekiq jobs are moved to SQS.

**Comment by sunil-sadasivan** [comment]
Now that Caseflow has been using SQS for the last few months, it's safe to say SQS is a robust and reliable queueing backend that scales well with our platform.   
 
The migration from Redis/Sidekiq to SQS/Shoryuken should be done with care, as it's a rather core change to existing functionality.  It's important to break this up into small, deployable steps for validation. 

# Steps 
##  1. Create SQS Queues (initial spec)

[We can follow this configuration for Caseflow.](https://github.com/department-of-veterans-affairs/appeals-deployment/issues/868#issuecomment-332873303)

`efolder_<env>_low_priority_dead_letter`
  - Queue to place failed low_priority messages... used for debugging of failed to process messages
`efolder_<env>_low_priority`
  - Low priority queue
  - This queue should be used for longer running, non-user-facing background jobs
`efolder_<env>_high_priority_dead_letter`
  - Queue to place failed high_priority messages used for debugging to process messages
`efolder_<env>_high_priority`
  - High priority queue
  - This queue should be used for any user facing jobs

`efolder_development_high_priority`
`efolder_development_low_priority`
  - These two queues can have open internet access.  This is used for local testing.  At the moment, this creates a single sqs queue for development testing.  This is one trade-off for going with a proprietary cloud queuing solution like SQS vs open source redis.  If we encounter conflicts for development we'll want to think about using something that fakes sqs locally (there are a few docker based solutions out there)

## 2. Install Shoryuken
Caseflow Example: https://github.com/department-of-veterans-affairs/caseflow/pull/3354/files

## 3. Replace Sidekiq ActiveJob adapter for Shoryuken
Caseflow Example: https://github.com/department-of-veterans-affairs/caseflow/pull/3385

This step switches out redis for SQS and each activejob will need to be configured to use the low or high priority queue.  This will need to be tested heavily in UAT before deploying to production. 

## 4. Remove Sidekiq references
Caseflow Example: https://github.com/department-of-veterans-affairs/caseflow/pull/3600

## Action items:
Because of this ticket, I am reviving this for creating sqs config in terraform, this fell off my radar. 🙈
https://github.com/department-of-veterans-affairs/appeals-deployment/issues/868

**Comment by mdbenjam** [comment]
Fixed
