### ISSUE TITLE
Status page eFolder Express

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-efolder#796]
### Context
During eFolder Express refactoring process, the status page takes a large amount of code (300 lines or so). However, the status page is currently the only way to capture these metrics. 

### Open Questions
- Can we capture these metrics via another method such as Google Analytics? 
- What are all the metrics we need from eFolder Express?

**Comment by Chingujo** [comment]
@cmgiven 

Assigning you to weigh in here as well =D.

**Comment by aroltsch** [comment]
@cmgiven We are working on eX v2; we implemented a completely new data model for the v2. You can find the new data model here: https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/docs/v2/database_structure.md. Once we connect Reader to the new v2 api, we are hoping to connect eX UI to the new API, that's why we are considering replacing the stats page with another tool.

**Comment by Chingujo** [comment]
@aroltsch 

Just got some context from @Chris. As long as he can the following in a given time period: 

Number of users
Number of downloads
Number of documents 

Then depurating the dashboard is fine.

**Comment by aroltsch** [comment]
This is not relevant anymore.
