### ISSUE TITLE
Search results page URL can display different pages

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow-efolder#891]
If Taylor searches for an efolder for a Veteran with ID 19891213 and the request for that efolder times out, she will be presented with the following page:
![image](https://user-images.githubusercontent.com/32683958/36318313-786f3646-130d-11e8-914a-7cac7608cc39.png)

However, since the job that actually attempts to fetch the manifest of that Veteran's efolder is never actually cancelled, if Taylor visited that page again (or emailed the URL to caseflow support for help troubleshooting the issue), it is quite possible that the efolder manifest fetch would have completed and she would be presented with the following page (with the same URL as before):
![image](https://user-images.githubusercontent.com/32683958/36318567-35b0909c-130e-11e8-9237-60fcea08d6ca.png)

I don't think this is a major bug worth solving at the moment, but it may cause confusion for our users (in which case I think the expedient solution is just to increase the timeout from its current 20 second threshold to something greater) so I wanted to document it with a bug.

v1 does not have this issue because the search results page never times out, we just keep spinning forever.

**Comment by Chingujo** [comment]
Thanks @lowellrex 

Agreed that this is a low priority bug and +1 to the timeout option. Worst case here is that they get to the start retrieving the file again. Extending the timeout seems like the easiest option. 

If I understand right, the user were to search for the claims file again, would it start a fresh manifest request or would it just show this retrieval page if it was successful. 

Two quick notes:
- I think we should change the error message. Since the user would not know what a manifest is. I believe we had a ticket for this way back and will try to dig it up. 
- just to be safe, this isn't PII is it =D?

**Comment by lowellrex** [comment]
If the user were to search for the same veteran ID again, it would start a new manifest request unless a manifest fetch had already been completed in which case it would show the search results page, correct.

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years.
