### ISSUE TITLE
Display notice on search results page if document source errored

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow-efolder#907]
Currently when a user searches for an efolder and one of the document sources (VVA or VBMS) is non-responsive, the only indication is the text that reads "10 from VBMS and 0 from VVA/LCM" (which could also be valid if there are truly no documents in VVA). When we encounter this situation on the [document download page](https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/904) we are more explicit in presenting an alert that something is wrong. We should mirror that behaviour here.

## Acceptance criteria
* Display a banner if any document source is unavailable

**Comment by lowellrex** [comment]
@Chingujo below is a mockup of what this looks like for this alert (swiped directly from efolder express v1 template). The "Try again" text links back to the root landing page with the search bar. Let me know if you think we should make any changes to the copy.

![image](https://user-images.githubusercontent.com/32683958/36763804-9be36294-1bf7-11e8-8a23-3886c8add0f9.png)

**Comment by Chingujo** [comment]
+1 to keeping spacing consistent and I will get back to you on the copy. We had a general theme to prevent calling out specific systems mid last year. 

Would also preference this and change it to a button keep it consistent with our other messaging. I will post a revised mock.

**Comment by lowellrex** [comment]
@Chingujo going to go ahead and close this out unless you think there are changes that need to be attached to this ticket in particular (I imagine styling changes can either be part of this ticket or a separate ticket just for those changes).

**Comment by Chingujo** [comment]
Sorry @lowellrex!

Hands tied the past few days. Will post a mock for this with revised copy and changing the try again to a button to be more consistent. Super fail on my end here

**Comment by lowellrex** [comment]
No sweat! Just wanted to make sure this didn't fall off your radar entirely.

**Comment by Chingujo** [comment]
@lowellrex 
Here is an updated error alert. Since we are a duo happy to hear your feedback as well. Even "this message is shown like never so we don't need to go crazy with it lolz." 

The goal was to create a more user friendly message and make more clear what the actionable steps are for the user. Wanted to make the back to eFolder express a button, however, having two primaries looked strange so made it in our secondary styling. Having two links (back to efolder express and send feedback) may cause confusion. 

<img width="578" alt="screen shot 2018-03-07 at 4 28 08 pm" src="https://user-images.githubusercontent.com/23316107/37119165-972a3038-2224-11e8-8971-4bab4cc69e73.png">

**Comment by lowellrex** [comment]
@Chingujo How does this look. The spacing is a little different than the mockup, but I'm happy living with that if you are!

![image](https://user-images.githubusercontent.com/32683958/37171392-90d2f91a-22c2-11e8-9f46-aabede6afcd7.png)

**Comment by Chingujo** [comment]
@lowellrex 

Amazing! Lgtm =D. Thanks Lowell!
