### ISSUE TITLE
Don't use string interpolation for filenames

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow-efolder#98]
This is a super bad pattern, never do this for file paths. This basically allows for SQL injection for files. An attacker could use this to write stuff out to the FS (such as a `../../../some/path/to/something.rb`) and get remote code execution.

https://github.com/madrobby/zaru/ looks to be pretty OK.

**Comment by KHarshawat** [comment]
Blocking WASA

**Comment by orischwartz** [comment]
This is impossible to exploit as currently configured because we prefix filenames with a unique index ([locally](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/services/download_documents.rb#L65) and in [s3](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/models/document.rb#L9)) so `File.open` will throw an error when that portion of the directory path isn't found (e.g., can't find `4-../../bin/rake`).

Still good practice to sanitize the file name though.
